wandb_version: 1

epochs:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 20
num_workers:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 5.0e-05
print_freq:
  desc: null
  value: 50
save_freq:
  desc: null
  value: 1000
sample_freq:
  desc: null
  value: 5000
sample_size:
  desc: null
  value: 4
resume_checkpoint:
  desc: null
  value: /raid/data_transfer/checkpoints_ddpm_lowres/model_epoch_241_step_19000.pt
data_root:
  desc: null
  value: /raid/data_transfer/
log_dir:
  desc: null
  value: /raid/data_transfer/chexray-diffusion/checkpoints_ddpm_lowres_newdata_finalft
checkpoint_dir:
  desc: null
  value: /raid/data_transfer/Train/checkpoints_jan_ddpm_lr_paired_new
model_params:
  desc: null
  value:
    dim: 16
    channels: 2
    out_dim: 1
    dim_mults:
    - 1
    - 2
    - 4
    - 8
    - 16
    - 32
    - 32
    - 32
schedule_params:
  desc: null
  value:
    name: cosine
    timesteps: 2000
diffusor_params:
  desc: null
  value: {}
loss_func:
  desc: null
  value: l1
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.1
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737233846
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.9.19
      5: 0.17.1
      6: 4.41.2
      8:
      - 5
      - 9
      13: linux-x86_64
